import verifyLegitimacy from '../src';

const pushWithBranch = {
  headers: {
    accept: '*/*',
    'content-length': '6921',
    'content-type': 'application/json',
    host: 'trigger-serverls-cd-shl-tnzlychixa.cn-hongkong.fcapp.run',
    'user-agent': 'GitHub-Hookshot/35a454f',
    'x-forwarded-proto': 'https',
    'x-github-delivery': '0fe82664-5f34-11ed-86a6-bdd5227f5620',
    'x-github-event': 'push',
    'x-github-hook-id': '386779078',
    'x-github-hook-installation-target-id': '559774849',
    'x-github-hook-installation-target-type': 'repository',
    'x-hub-signature': 'sha1=1cc8f28a488b81315b46003a694bcfbac086d600',
    'x-hub-signature-256':
      'sha256=1e420f4752d6b5c1b6a22a86abbcdf6a7b0be3ff8841cc29cce8930e288f0d9e',
  },
  body: {
    ref: 'refs/heads/main',
    before: 'f8e04156de1870fe9c1010db59b0f87a2d5db42a',
    after: '6b956d234e19ebf2ab68a5df906d8c7f2afc51d2',
    repository: {
      id: 559774849,
      node_id: 'R_kgDOIV18gQ',
      name: 'test-cd',
      full_name: 'xsahxl/test-cd',
      private: true,
      owner: {
        name: 'xsahxl',
        email: 'xsahxl@126.com',
        login: 'xsahxl',
        id: 21330840,
        node_id: 'MDQ6VXNlcjIxMzMwODQw',
        avatar_url: 'https://avatars.githubusercontent.com/u/21330840?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/xsahxl',
        html_url: 'https://github.com/xsahxl',
        followers_url: 'https://api.github.com/users/xsahxl/followers',
        following_url: 'https://api.github.com/users/xsahxl/following{/other_user}',
        gists_url: 'https://api.github.com/users/xsahxl/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/xsahxl/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/xsahxl/subscriptions',
        organizations_url: 'https://api.github.com/users/xsahxl/orgs',
        repos_url: 'https://api.github.com/users/xsahxl/repos',
        events_url: 'https://api.github.com/users/xsahxl/events{/privacy}',
        received_events_url: 'https://api.github.com/users/xsahxl/received_events',
        type: 'User',
        site_admin: false,
      },
      html_url: 'https://github.com/xsahxl/test-cd',
      description: null,
      fork: false,
      url: 'https://github.com/xsahxl/test-cd',
      forks_url: 'https://api.github.com/repos/xsahxl/test-cd/forks',
      keys_url: 'https://api.github.com/repos/xsahxl/test-cd/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/xsahxl/test-cd/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/xsahxl/test-cd/teams',
      hooks_url: 'https://api.github.com/repos/xsahxl/test-cd/hooks',
      issue_events_url: 'https://api.github.com/repos/xsahxl/test-cd/issues/events{/number}',
      events_url: 'https://api.github.com/repos/xsahxl/test-cd/events',
      assignees_url: 'https://api.github.com/repos/xsahxl/test-cd/assignees{/user}',
      branches_url: 'https://api.github.com/repos/xsahxl/test-cd/branches{/branch}',
      tags_url: 'https://api.github.com/repos/xsahxl/test-cd/tags',
      blobs_url: 'https://api.github.com/repos/xsahxl/test-cd/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/xsahxl/test-cd/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/xsahxl/test-cd/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/xsahxl/test-cd/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/xsahxl/test-cd/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/xsahxl/test-cd/languages',
      stargazers_url: 'https://api.github.com/repos/xsahxl/test-cd/stargazers',
      contributors_url: 'https://api.github.com/repos/xsahxl/test-cd/contributors',
      subscribers_url: 'https://api.github.com/repos/xsahxl/test-cd/subscribers',
      subscription_url: 'https://api.github.com/repos/xsahxl/test-cd/subscription',
      commits_url: 'https://api.github.com/repos/xsahxl/test-cd/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/xsahxl/test-cd/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/xsahxl/test-cd/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/xsahxl/test-cd/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/xsahxl/test-cd/contents/{+path}',
      compare_url: 'https://api.github.com/repos/xsahxl/test-cd/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/xsahxl/test-cd/merges',
      archive_url: 'https://api.github.com/repos/xsahxl/test-cd/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/xsahxl/test-cd/downloads',
      issues_url: 'https://api.github.com/repos/xsahxl/test-cd/issues{/number}',
      pulls_url: 'https://api.github.com/repos/xsahxl/test-cd/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/xsahxl/test-cd/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/xsahxl/test-cd/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/xsahxl/test-cd/labels{/name}',
      releases_url: 'https://api.github.com/repos/xsahxl/test-cd/releases{/id}',
      deployments_url: 'https://api.github.com/repos/xsahxl/test-cd/deployments',
      created_at: 1667189046,
      updated_at: '2022-10-31T04:04:06Z',
      pushed_at: 1667891272,
      git_url: 'git://github.com/xsahxl/test-cd.git',
      ssh_url: 'git@github.com:xsahxl/test-cd.git',
      clone_url: 'https://github.com/xsahxl/test-cd.git',
      svn_url: 'https://github.com/xsahxl/test-cd',
      homepage: null,
      size: 1,
      stargazers_count: 0,
      watchers_count: 0,
      language: null,
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'private',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'main',
      stargazers: 0,
      master_branch: 'main',
    },
    pusher: {
      name: 'xsahxl',
      email: 'xsahxl@126.com',
    },
    sender: {
      login: 'xsahxl',
      id: 21330840,
      node_id: 'MDQ6VXNlcjIxMzMwODQw',
      avatar_url: 'https://avatars.githubusercontent.com/u/21330840?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/xsahxl',
      html_url: 'https://github.com/xsahxl',
      followers_url: 'https://api.github.com/users/xsahxl/followers',
      following_url: 'https://api.github.com/users/xsahxl/following{/other_user}',
      gists_url: 'https://api.github.com/users/xsahxl/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/xsahxl/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/xsahxl/subscriptions',
      organizations_url: 'https://api.github.com/users/xsahxl/orgs',
      repos_url: 'https://api.github.com/users/xsahxl/repos',
      events_url: 'https://api.github.com/users/xsahxl/events{/privacy}',
      received_events_url: 'https://api.github.com/users/xsahxl/received_events',
      type: 'User',
      site_admin: false,
    },
    created: false,
    deleted: false,
    forced: false,
    base_ref: null,
    compare: 'https://github.com/xsahxl/test-cd/compare/f8e04156de18...6b956d234e19',
    commits: [
      {
        id: '6b956d234e19ebf2ab68a5df906d8c7f2afc51d2',
        tree_id: 'b2f259dd6efe08e83eb23c9743cae22983832168',
        distinct: true,
        message: 'Update readme.md',
        timestamp: '2022-11-08T15:07:52+08:00',
        url: 'https://github.com/xsahxl/test-cd/commit/6b956d234e19ebf2ab68a5df906d8c7f2afc51d2',
        author: {
          name: 'xsahxl',
          email: 'xsahxl@126.com',
          username: 'xsahxl',
        },
        committer: {
          name: 'GitHub',
          email: 'noreply@github.com',
          username: 'web-flow',
        },
        added: [],
        removed: [],
        modified: ['readme.md'],
      },
    ],
    head_commit: {
      id: '6b956d234e19ebf2ab68a5df906d8c7f2afc51d2',
      tree_id: 'b2f259dd6efe08e83eb23c9743cae22983832168',
      distinct: true,
      message: 'Update readme.md',
      timestamp: '2022-11-08T15:07:52+08:00',
      url: 'https://github.com/xsahxl/test-cd/commit/6b956d234e19ebf2ab68a5df906d8c7f2afc51d2',
      author: {
        name: 'xsahxl',
        email: 'xsahxl@126.com',
        username: 'xsahxl',
      },
      committer: {
        name: 'GitHub',
        email: 'noreply@github.com',
        username: 'web-flow',
      },
      added: [],
      removed: [],
      modified: ['readme.md'],
    },
  },
};

const pushWithTag = {
  headers: {
    accept: '*/*',
    'content-length': '6921',
    'content-type': 'application/json',
    host: 'trigger-serverls-cd-shl-tnzlychixa.cn-hongkong.fcapp.run',
    'user-agent': 'GitHub-Hookshot/35a454f',
    'x-forwarded-proto': 'https',
    'x-github-delivery': '0fe82664-5f34-11ed-86a6-bdd5227f5620',
    'x-github-event': 'push',
    'x-github-hook-id': '386779078',
    'x-github-hook-installation-target-id': '559774849',
    'x-github-hook-installation-target-type': 'repository',
    'x-hub-signature-256':
      'sha256=1e420f4752d6b5c1b6a22a86abbcdf6a7b0be3ff8841cc29cce8930e288f0d9e',
  },
  body: {
    ref: 'refs/tags/v0.0.1',
    before: '0000000000000000000000000000000000000000',
    after: '6b956d234e19ebf2ab68a5df906d8c7f2afc51d2',
    repository: {
      id: 559774849,
      node_id: 'R_kgDOIV18gQ',
      name: 'test-cd',
      full_name: 'xsahxl/test-cd',
      private: true,
      owner: {
        name: 'xsahxl',
        email: 'xsahxl@126.com',
        login: 'xsahxl',
        id: 21330840,
        node_id: 'MDQ6VXNlcjIxMzMwODQw',
        avatar_url: 'https://avatars.githubusercontent.com/u/21330840?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/xsahxl',
        html_url: 'https://github.com/xsahxl',
        followers_url: 'https://api.github.com/users/xsahxl/followers',
        following_url: 'https://api.github.com/users/xsahxl/following{/other_user}',
        gists_url: 'https://api.github.com/users/xsahxl/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/xsahxl/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/xsahxl/subscriptions',
        organizations_url: 'https://api.github.com/users/xsahxl/orgs',
        repos_url: 'https://api.github.com/users/xsahxl/repos',
        events_url: 'https://api.github.com/users/xsahxl/events{/privacy}',
        received_events_url: 'https://api.github.com/users/xsahxl/received_events',
        type: 'User',
        site_admin: false,
      },
      html_url: 'https://github.com/xsahxl/test-cd',
      description: null,
      fork: false,
      url: 'https://github.com/xsahxl/test-cd',
      forks_url: 'https://api.github.com/repos/xsahxl/test-cd/forks',
      keys_url: 'https://api.github.com/repos/xsahxl/test-cd/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/xsahxl/test-cd/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/xsahxl/test-cd/teams',
      hooks_url: 'https://api.github.com/repos/xsahxl/test-cd/hooks',
      issue_events_url: 'https://api.github.com/repos/xsahxl/test-cd/issues/events{/number}',
      events_url: 'https://api.github.com/repos/xsahxl/test-cd/events',
      assignees_url: 'https://api.github.com/repos/xsahxl/test-cd/assignees{/user}',
      branches_url: 'https://api.github.com/repos/xsahxl/test-cd/branches{/branch}',
      tags_url: 'https://api.github.com/repos/xsahxl/test-cd/tags',
      blobs_url: 'https://api.github.com/repos/xsahxl/test-cd/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/xsahxl/test-cd/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/xsahxl/test-cd/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/xsahxl/test-cd/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/xsahxl/test-cd/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/xsahxl/test-cd/languages',
      stargazers_url: 'https://api.github.com/repos/xsahxl/test-cd/stargazers',
      contributors_url: 'https://api.github.com/repos/xsahxl/test-cd/contributors',
      subscribers_url: 'https://api.github.com/repos/xsahxl/test-cd/subscribers',
      subscription_url: 'https://api.github.com/repos/xsahxl/test-cd/subscription',
      commits_url: 'https://api.github.com/repos/xsahxl/test-cd/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/xsahxl/test-cd/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/xsahxl/test-cd/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/xsahxl/test-cd/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/xsahxl/test-cd/contents/{+path}',
      compare_url: 'https://api.github.com/repos/xsahxl/test-cd/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/xsahxl/test-cd/merges',
      archive_url: 'https://api.github.com/repos/xsahxl/test-cd/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/xsahxl/test-cd/downloads',
      issues_url: 'https://api.github.com/repos/xsahxl/test-cd/issues{/number}',
      pulls_url: 'https://api.github.com/repos/xsahxl/test-cd/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/xsahxl/test-cd/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/xsahxl/test-cd/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/xsahxl/test-cd/labels{/name}',
      releases_url: 'https://api.github.com/repos/xsahxl/test-cd/releases{/id}',
      deployments_url: 'https://api.github.com/repos/xsahxl/test-cd/deployments',
      created_at: 1667189046,
      updated_at: '2022-10-31T04:04:06Z',
      pushed_at: 1668065187,
      git_url: 'git://github.com/xsahxl/test-cd.git',
      ssh_url: 'git@github.com:xsahxl/test-cd.git',
      clone_url: 'https://github.com/xsahxl/test-cd.git',
      svn_url: 'https://github.com/xsahxl/test-cd',
      homepage: null,
      size: 1,
      stargazers_count: 0,
      watchers_count: 0,
      language: null,
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'private',
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: 'main',
      stargazers: 0,
      master_branch: 'main',
    },
    pusher: {
      name: 'xsahxl',
      email: 'xsahxl@126.com',
    },
    sender: {
      login: 'xsahxl',
      id: 21330840,
      node_id: 'MDQ6VXNlcjIxMzMwODQw',
      avatar_url: 'https://avatars.githubusercontent.com/u/21330840?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/xsahxl',
      html_url: 'https://github.com/xsahxl',
      followers_url: 'https://api.github.com/users/xsahxl/followers',
      following_url: 'https://api.github.com/users/xsahxl/following{/other_user}',
      gists_url: 'https://api.github.com/users/xsahxl/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/xsahxl/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/xsahxl/subscriptions',
      organizations_url: 'https://api.github.com/users/xsahxl/orgs',
      repos_url: 'https://api.github.com/users/xsahxl/repos',
      events_url: 'https://api.github.com/users/xsahxl/events{/privacy}',
      received_events_url: 'https://api.github.com/users/xsahxl/received_events',
      type: 'User',
      site_admin: false,
    },
    created: true,
    deleted: false,
    forced: false,
    base_ref: 'refs/heads/main',
    compare: 'https://github.com/xsahxl/test-cd/compare/v0.0.1',
    commits: [],
    head_commit: {
      id: '6b956d234e19ebf2ab68a5df906d8c7f2afc51d2',
      tree_id: 'b2f259dd6efe08e83eb23c9743cae22983832168',
      distinct: true,
      message: 'Update readme.md',
      timestamp: '2022-11-08T15:07:52+08:00',
      url: 'https://github.com/xsahxl/test-cd/commit/6b956d234e19ebf2ab68a5df906d8c7f2afc51d2',
      author: {
        name: 'xsahxl',
        email: 'xsahxl@126.com',
        username: 'xsahxl',
      },
      committer: {
        name: 'GitHub',
        email: 'noreply@github.com',
        username: 'web-flow',
      },
      added: [],
      removed: [],
      modified: ['readme.md'],
    },
  },
};

const prInputs = {
  headers: {
    accept: '*/*',
    'content-length': '6921',
    'content-type': 'application/json',
    host: 'trigger-serverls-cd-shl-tnzlychixa.cn-hongkong.fcapp.run',
    'user-agent': 'GitHub-Hookshot/35a454f',
    'x-forwarded-proto': 'https',
    'x-github-delivery': '0fe82664-5f34-11ed-86a6-bdd5227f5620',
    'x-github-event': 'pull_request',
    'x-github-hook-id': '386779078',
    'x-github-hook-installation-target-id': '559774849',
    'x-github-hook-installation-target-type': 'repository',
    'x-hub-signature-256':
      'sha256=1e420f4752d6b5c1b6a22a86abbcdf6a7b0be3ff8841cc29cce8930e288f0d9e',
  },
  body: {
    action: 'opened',
    number: 2,
    pull_request: {
      url: 'https://api.github.com/repos/xsahxl/test-cd/pulls/2',
      id: 1117303846,
      node_id: 'PR_kwDOIV18gc5CmLQm',
      html_url: 'https://github.com/xsahxl/test-cd/pull/2',
      diff_url: 'https://github.com/xsahxl/test-cd/pull/2.diff',
      patch_url: 'https://github.com/xsahxl/test-cd/pull/2.patch',
      issue_url: 'https://api.github.com/repos/xsahxl/test-cd/issues/2',
      number: 2,
      state: 'open',
      locked: false,
      title: 'Update readme.md',
      user: {
        login: 'xsahxl',
        id: 21330840,
        node_id: 'MDQ6VXNlcjIxMzMwODQw',
        avatar_url: 'https://avatars.githubusercontent.com/u/21330840?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/xsahxl',
        html_url: 'https://github.com/xsahxl',
        followers_url: 'https://api.github.com/users/xsahxl/followers',
        following_url: 'https://api.github.com/users/xsahxl/following{/other_user}',
        gists_url: 'https://api.github.com/users/xsahxl/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/xsahxl/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/xsahxl/subscriptions',
        organizations_url: 'https://api.github.com/users/xsahxl/orgs',
        repos_url: 'https://api.github.com/users/xsahxl/repos',
        events_url: 'https://api.github.com/users/xsahxl/events{/privacy}',
        received_events_url: 'https://api.github.com/users/xsahxl/received_events',
        type: 'User',
        site_admin: false,
      },
      body: null,
      created_at: '2022-11-10T08:13:04Z',
      updated_at: '2022-11-10T08:13:04Z',
      closed_at: null,
      merged_at: null,
      merge_commit_sha: null,
      assignee: null,
      assignees: [],
      requested_reviewers: [],
      requested_teams: [],
      labels: [],
      milestone: null,
      draft: false,
      commits_url: 'https://api.github.com/repos/xsahxl/test-cd/pulls/2/commits',
      review_comments_url: 'https://api.github.com/repos/xsahxl/test-cd/pulls/2/comments',
      review_comment_url: 'https://api.github.com/repos/xsahxl/test-cd/pulls/comments{/number}',
      comments_url: 'https://api.github.com/repos/xsahxl/test-cd/issues/2/comments',
      statuses_url:
        'https://api.github.com/repos/xsahxl/test-cd/statuses/3c8d45464f8998997abbb9ed5278e62df5bb2e15',
      head: {
        label: 'xsahxl:dev',
        ref: 'dev',
        sha: '3c8d45464f8998997abbb9ed5278e62df5bb2e15',
        user: {
          login: 'xsahxl',
          id: 21330840,
          node_id: 'MDQ6VXNlcjIxMzMwODQw',
          avatar_url: 'https://avatars.githubusercontent.com/u/21330840?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/xsahxl',
          html_url: 'https://github.com/xsahxl',
          followers_url: 'https://api.github.com/users/xsahxl/followers',
          following_url: 'https://api.github.com/users/xsahxl/following{/other_user}',
          gists_url: 'https://api.github.com/users/xsahxl/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/xsahxl/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/xsahxl/subscriptions',
          organizations_url: 'https://api.github.com/users/xsahxl/orgs',
          repos_url: 'https://api.github.com/users/xsahxl/repos',
          events_url: 'https://api.github.com/users/xsahxl/events{/privacy}',
          received_events_url: 'https://api.github.com/users/xsahxl/received_events',
          type: 'User',
          site_admin: false,
        },
        repo: {
          id: 559774849,
          node_id: 'R_kgDOIV18gQ',
          name: 'test-cd',
          full_name: 'xsahxl/test-cd',
          private: true,
          owner: {
            login: 'xsahxl',
            id: 21330840,
            node_id: 'MDQ6VXNlcjIxMzMwODQw',
            avatar_url: 'https://avatars.githubusercontent.com/u/21330840?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/xsahxl',
            html_url: 'https://github.com/xsahxl',
            followers_url: 'https://api.github.com/users/xsahxl/followers',
            following_url: 'https://api.github.com/users/xsahxl/following{/other_user}',
            gists_url: 'https://api.github.com/users/xsahxl/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/xsahxl/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/xsahxl/subscriptions',
            organizations_url: 'https://api.github.com/users/xsahxl/orgs',
            repos_url: 'https://api.github.com/users/xsahxl/repos',
            events_url: 'https://api.github.com/users/xsahxl/events{/privacy}',
            received_events_url: 'https://api.github.com/users/xsahxl/received_events',
            type: 'User',
            site_admin: false,
          },
          html_url: 'https://github.com/xsahxl/test-cd',
          description: null,
          fork: false,
          url: 'https://api.github.com/repos/xsahxl/test-cd',
          forks_url: 'https://api.github.com/repos/xsahxl/test-cd/forks',
          keys_url: 'https://api.github.com/repos/xsahxl/test-cd/keys{/key_id}',
          collaborators_url:
            'https://api.github.com/repos/xsahxl/test-cd/collaborators{/collaborator}',
          teams_url: 'https://api.github.com/repos/xsahxl/test-cd/teams',
          hooks_url: 'https://api.github.com/repos/xsahxl/test-cd/hooks',
          issue_events_url: 'https://api.github.com/repos/xsahxl/test-cd/issues/events{/number}',
          events_url: 'https://api.github.com/repos/xsahxl/test-cd/events',
          assignees_url: 'https://api.github.com/repos/xsahxl/test-cd/assignees{/user}',
          branches_url: 'https://api.github.com/repos/xsahxl/test-cd/branches{/branch}',
          tags_url: 'https://api.github.com/repos/xsahxl/test-cd/tags',
          blobs_url: 'https://api.github.com/repos/xsahxl/test-cd/git/blobs{/sha}',
          git_tags_url: 'https://api.github.com/repos/xsahxl/test-cd/git/tags{/sha}',
          git_refs_url: 'https://api.github.com/repos/xsahxl/test-cd/git/refs{/sha}',
          trees_url: 'https://api.github.com/repos/xsahxl/test-cd/git/trees{/sha}',
          statuses_url: 'https://api.github.com/repos/xsahxl/test-cd/statuses/{sha}',
          languages_url: 'https://api.github.com/repos/xsahxl/test-cd/languages',
          stargazers_url: 'https://api.github.com/repos/xsahxl/test-cd/stargazers',
          contributors_url: 'https://api.github.com/repos/xsahxl/test-cd/contributors',
          subscribers_url: 'https://api.github.com/repos/xsahxl/test-cd/subscribers',
          subscription_url: 'https://api.github.com/repos/xsahxl/test-cd/subscription',
          commits_url: 'https://api.github.com/repos/xsahxl/test-cd/commits{/sha}',
          git_commits_url: 'https://api.github.com/repos/xsahxl/test-cd/git/commits{/sha}',
          comments_url: 'https://api.github.com/repos/xsahxl/test-cd/comments{/number}',
          issue_comment_url: 'https://api.github.com/repos/xsahxl/test-cd/issues/comments{/number}',
          contents_url: 'https://api.github.com/repos/xsahxl/test-cd/contents/{+path}',
          compare_url: 'https://api.github.com/repos/xsahxl/test-cd/compare/{base}...{head}',
          merges_url: 'https://api.github.com/repos/xsahxl/test-cd/merges',
          archive_url: 'https://api.github.com/repos/xsahxl/test-cd/{archive_format}{/ref}',
          downloads_url: 'https://api.github.com/repos/xsahxl/test-cd/downloads',
          issues_url: 'https://api.github.com/repos/xsahxl/test-cd/issues{/number}',
          pulls_url: 'https://api.github.com/repos/xsahxl/test-cd/pulls{/number}',
          milestones_url: 'https://api.github.com/repos/xsahxl/test-cd/milestones{/number}',
          notifications_url:
            'https://api.github.com/repos/xsahxl/test-cd/notifications{?since,all,participating}',
          labels_url: 'https://api.github.com/repos/xsahxl/test-cd/labels{/name}',
          releases_url: 'https://api.github.com/repos/xsahxl/test-cd/releases{/id}',
          deployments_url: 'https://api.github.com/repos/xsahxl/test-cd/deployments',
          created_at: '2022-10-31T04:04:06Z',
          updated_at: '2022-10-31T04:04:06Z',
          pushed_at: '2022-11-10T08:13:04Z',
          git_url: 'git://github.com/xsahxl/test-cd.git',
          ssh_url: 'git@github.com:xsahxl/test-cd.git',
          clone_url: 'https://github.com/xsahxl/test-cd.git',
          svn_url: 'https://github.com/xsahxl/test-cd',
          homepage: null,
          size: 1,
          stargazers_count: 0,
          watchers_count: 0,
          language: null,
          has_issues: true,
          has_projects: true,
          has_downloads: true,
          has_wiki: true,
          has_pages: false,
          has_discussions: false,
          forks_count: 0,
          mirror_url: null,
          archived: false,
          disabled: false,
          open_issues_count: 1,
          license: null,
          allow_forking: true,
          is_template: false,
          web_commit_signoff_required: false,
          topics: [],
          visibility: 'private',
          forks: 0,
          open_issues: 1,
          watchers: 0,
          default_branch: 'main',
          allow_squash_merge: true,
          allow_merge_commit: true,
          allow_rebase_merge: true,
          allow_auto_merge: false,
          delete_branch_on_merge: false,
          allow_update_branch: false,
          use_squash_pr_title_as_default: false,
          squash_merge_commit_message: 'COMMIT_MESSAGES',
          squash_merge_commit_title: 'COMMIT_OR_PR_TITLE',
          merge_commit_message: 'PR_TITLE',
          merge_commit_title: 'MERGE_MESSAGE',
        },
      },
      base: {
        label: 'xsahxl:main',
        ref: 'main',
        sha: 'f3a381b3531f095c0484e728c15c791738fae5d8',
        user: {
          login: 'xsahxl',
          id: 21330840,
          node_id: 'MDQ6VXNlcjIxMzMwODQw',
          avatar_url: 'https://avatars.githubusercontent.com/u/21330840?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/xsahxl',
          html_url: 'https://github.com/xsahxl',
          followers_url: 'https://api.github.com/users/xsahxl/followers',
          following_url: 'https://api.github.com/users/xsahxl/following{/other_user}',
          gists_url: 'https://api.github.com/users/xsahxl/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/xsahxl/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/xsahxl/subscriptions',
          organizations_url: 'https://api.github.com/users/xsahxl/orgs',
          repos_url: 'https://api.github.com/users/xsahxl/repos',
          events_url: 'https://api.github.com/users/xsahxl/events{/privacy}',
          received_events_url: 'https://api.github.com/users/xsahxl/received_events',
          type: 'User',
          site_admin: false,
        },
        repo: {
          id: 559774849,
          node_id: 'R_kgDOIV18gQ',
          name: 'test-cd',
          full_name: 'xsahxl/test-cd',
          private: true,
          owner: {
            login: 'xsahxl',
            id: 21330840,
            node_id: 'MDQ6VXNlcjIxMzMwODQw',
            avatar_url: 'https://avatars.githubusercontent.com/u/21330840?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/xsahxl',
            html_url: 'https://github.com/xsahxl',
            followers_url: 'https://api.github.com/users/xsahxl/followers',
            following_url: 'https://api.github.com/users/xsahxl/following{/other_user}',
            gists_url: 'https://api.github.com/users/xsahxl/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/xsahxl/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/xsahxl/subscriptions',
            organizations_url: 'https://api.github.com/users/xsahxl/orgs',
            repos_url: 'https://api.github.com/users/xsahxl/repos',
            events_url: 'https://api.github.com/users/xsahxl/events{/privacy}',
            received_events_url: 'https://api.github.com/users/xsahxl/received_events',
            type: 'User',
            site_admin: false,
          },
          html_url: 'https://github.com/xsahxl/test-cd',
          description: null,
          fork: false,
          url: 'https://api.github.com/repos/xsahxl/test-cd',
          forks_url: 'https://api.github.com/repos/xsahxl/test-cd/forks',
          keys_url: 'https://api.github.com/repos/xsahxl/test-cd/keys{/key_id}',
          collaborators_url:
            'https://api.github.com/repos/xsahxl/test-cd/collaborators{/collaborator}',
          teams_url: 'https://api.github.com/repos/xsahxl/test-cd/teams',
          hooks_url: 'https://api.github.com/repos/xsahxl/test-cd/hooks',
          issue_events_url: 'https://api.github.com/repos/xsahxl/test-cd/issues/events{/number}',
          events_url: 'https://api.github.com/repos/xsahxl/test-cd/events',
          assignees_url: 'https://api.github.com/repos/xsahxl/test-cd/assignees{/user}',
          branches_url: 'https://api.github.com/repos/xsahxl/test-cd/branches{/branch}',
          tags_url: 'https://api.github.com/repos/xsahxl/test-cd/tags',
          blobs_url: 'https://api.github.com/repos/xsahxl/test-cd/git/blobs{/sha}',
          git_tags_url: 'https://api.github.com/repos/xsahxl/test-cd/git/tags{/sha}',
          git_refs_url: 'https://api.github.com/repos/xsahxl/test-cd/git/refs{/sha}',
          trees_url: 'https://api.github.com/repos/xsahxl/test-cd/git/trees{/sha}',
          statuses_url: 'https://api.github.com/repos/xsahxl/test-cd/statuses/{sha}',
          languages_url: 'https://api.github.com/repos/xsahxl/test-cd/languages',
          stargazers_url: 'https://api.github.com/repos/xsahxl/test-cd/stargazers',
          contributors_url: 'https://api.github.com/repos/xsahxl/test-cd/contributors',
          subscribers_url: 'https://api.github.com/repos/xsahxl/test-cd/subscribers',
          subscription_url: 'https://api.github.com/repos/xsahxl/test-cd/subscription',
          commits_url: 'https://api.github.com/repos/xsahxl/test-cd/commits{/sha}',
          git_commits_url: 'https://api.github.com/repos/xsahxl/test-cd/git/commits{/sha}',
          comments_url: 'https://api.github.com/repos/xsahxl/test-cd/comments{/number}',
          issue_comment_url: 'https://api.github.com/repos/xsahxl/test-cd/issues/comments{/number}',
          contents_url: 'https://api.github.com/repos/xsahxl/test-cd/contents/{+path}',
          compare_url: 'https://api.github.com/repos/xsahxl/test-cd/compare/{base}...{head}',
          merges_url: 'https://api.github.com/repos/xsahxl/test-cd/merges',
          archive_url: 'https://api.github.com/repos/xsahxl/test-cd/{archive_format}{/ref}',
          downloads_url: 'https://api.github.com/repos/xsahxl/test-cd/downloads',
          issues_url: 'https://api.github.com/repos/xsahxl/test-cd/issues{/number}',
          pulls_url: 'https://api.github.com/repos/xsahxl/test-cd/pulls{/number}',
          milestones_url: 'https://api.github.com/repos/xsahxl/test-cd/milestones{/number}',
          notifications_url:
            'https://api.github.com/repos/xsahxl/test-cd/notifications{?since,all,participating}',
          labels_url: 'https://api.github.com/repos/xsahxl/test-cd/labels{/name}',
          releases_url: 'https://api.github.com/repos/xsahxl/test-cd/releases{/id}',
          deployments_url: 'https://api.github.com/repos/xsahxl/test-cd/deployments',
          created_at: '2022-10-31T04:04:06Z',
          updated_at: '2022-10-31T04:04:06Z',
          pushed_at: '2022-11-10T08:13:04Z',
          git_url: 'git://github.com/xsahxl/test-cd.git',
          ssh_url: 'git@github.com:xsahxl/test-cd.git',
          clone_url: 'https://github.com/xsahxl/test-cd.git',
          svn_url: 'https://github.com/xsahxl/test-cd',
          homepage: null,
          size: 1,
          stargazers_count: 0,
          watchers_count: 0,
          language: null,
          has_issues: true,
          has_projects: true,
          has_downloads: true,
          has_wiki: true,
          has_pages: false,
          has_discussions: false,
          forks_count: 0,
          mirror_url: null,
          archived: false,
          disabled: false,
          open_issues_count: 1,
          license: null,
          allow_forking: true,
          is_template: false,
          web_commit_signoff_required: false,
          topics: [],
          visibility: 'private',
          forks: 0,
          open_issues: 1,
          watchers: 0,
          default_branch: 'main',
          allow_squash_merge: true,
          allow_merge_commit: true,
          allow_rebase_merge: true,
          allow_auto_merge: false,
          delete_branch_on_merge: false,
          allow_update_branch: false,
          use_squash_pr_title_as_default: false,
          squash_merge_commit_message: 'COMMIT_MESSAGES',
          squash_merge_commit_title: 'COMMIT_OR_PR_TITLE',
          merge_commit_message: 'PR_TITLE',
          merge_commit_title: 'MERGE_MESSAGE',
        },
      },
      _links: {
        self: {
          href: 'https://api.github.com/repos/xsahxl/test-cd/pulls/2',
        },
        html: {
          href: 'https://github.com/xsahxl/test-cd/pull/2',
        },
        issue: {
          href: 'https://api.github.com/repos/xsahxl/test-cd/issues/2',
        },
        comments: {
          href: 'https://api.github.com/repos/xsahxl/test-cd/issues/2/comments',
        },
        review_comments: {
          href: 'https://api.github.com/repos/xsahxl/test-cd/pulls/2/comments',
        },
        review_comment: {
          href: 'https://api.github.com/repos/xsahxl/test-cd/pulls/comments{/number}',
        },
        commits: {
          href: 'https://api.github.com/repos/xsahxl/test-cd/pulls/2/commits',
        },
        statuses: {
          href: 'https://api.github.com/repos/xsahxl/test-cd/statuses/3c8d45464f8998997abbb9ed5278e62df5bb2e15',
        },
      },
      author_association: 'OWNER',
      auto_merge: null,
      active_lock_reason: null,
      merged: false,
      mergeable: null,
      rebaseable: null,
      mergeable_state: 'unknown',
      merged_by: null,
      comments: 0,
      review_comments: 0,
      maintainer_can_modify: false,
      commits: 1,
      additions: 1,
      deletions: 1,
      changed_files: 1,
    },
    repository: {
      id: 559774849,
      node_id: 'R_kgDOIV18gQ',
      name: 'test-cd',
      full_name: 'xsahxl/test-cd',
      private: true,
      owner: {
        login: 'xsahxl',
        id: 21330840,
        node_id: 'MDQ6VXNlcjIxMzMwODQw',
        avatar_url: 'https://avatars.githubusercontent.com/u/21330840?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/xsahxl',
        html_url: 'https://github.com/xsahxl',
        followers_url: 'https://api.github.com/users/xsahxl/followers',
        following_url: 'https://api.github.com/users/xsahxl/following{/other_user}',
        gists_url: 'https://api.github.com/users/xsahxl/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/xsahxl/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/xsahxl/subscriptions',
        organizations_url: 'https://api.github.com/users/xsahxl/orgs',
        repos_url: 'https://api.github.com/users/xsahxl/repos',
        events_url: 'https://api.github.com/users/xsahxl/events{/privacy}',
        received_events_url: 'https://api.github.com/users/xsahxl/received_events',
        type: 'User',
        site_admin: false,
      },
      html_url: 'https://github.com/xsahxl/test-cd',
      description: null,
      fork: false,
      url: 'https://api.github.com/repos/xsahxl/test-cd',
      forks_url: 'https://api.github.com/repos/xsahxl/test-cd/forks',
      keys_url: 'https://api.github.com/repos/xsahxl/test-cd/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/xsahxl/test-cd/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/xsahxl/test-cd/teams',
      hooks_url: 'https://api.github.com/repos/xsahxl/test-cd/hooks',
      issue_events_url: 'https://api.github.com/repos/xsahxl/test-cd/issues/events{/number}',
      events_url: 'https://api.github.com/repos/xsahxl/test-cd/events',
      assignees_url: 'https://api.github.com/repos/xsahxl/test-cd/assignees{/user}',
      branches_url: 'https://api.github.com/repos/xsahxl/test-cd/branches{/branch}',
      tags_url: 'https://api.github.com/repos/xsahxl/test-cd/tags',
      blobs_url: 'https://api.github.com/repos/xsahxl/test-cd/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/xsahxl/test-cd/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/xsahxl/test-cd/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/xsahxl/test-cd/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/xsahxl/test-cd/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/xsahxl/test-cd/languages',
      stargazers_url: 'https://api.github.com/repos/xsahxl/test-cd/stargazers',
      contributors_url: 'https://api.github.com/repos/xsahxl/test-cd/contributors',
      subscribers_url: 'https://api.github.com/repos/xsahxl/test-cd/subscribers',
      subscription_url: 'https://api.github.com/repos/xsahxl/test-cd/subscription',
      commits_url: 'https://api.github.com/repos/xsahxl/test-cd/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/xsahxl/test-cd/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/xsahxl/test-cd/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/xsahxl/test-cd/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/xsahxl/test-cd/contents/{+path}',
      compare_url: 'https://api.github.com/repos/xsahxl/test-cd/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/xsahxl/test-cd/merges',
      archive_url: 'https://api.github.com/repos/xsahxl/test-cd/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/xsahxl/test-cd/downloads',
      issues_url: 'https://api.github.com/repos/xsahxl/test-cd/issues{/number}',
      pulls_url: 'https://api.github.com/repos/xsahxl/test-cd/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/xsahxl/test-cd/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/xsahxl/test-cd/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/xsahxl/test-cd/labels{/name}',
      releases_url: 'https://api.github.com/repos/xsahxl/test-cd/releases{/id}',
      deployments_url: 'https://api.github.com/repos/xsahxl/test-cd/deployments',
      created_at: '2022-10-31T04:04:06Z',
      updated_at: '2022-10-31T04:04:06Z',
      pushed_at: '2022-11-10T08:13:04Z',
      git_url: 'git://github.com/xsahxl/test-cd.git',
      ssh_url: 'git@github.com:xsahxl/test-cd.git',
      clone_url: 'https://github.com/xsahxl/test-cd.git',
      svn_url: 'https://github.com/xsahxl/test-cd',
      homepage: null,
      size: 1,
      stargazers_count: 0,
      watchers_count: 0,
      language: null,
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 1,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'private',
      forks: 0,
      open_issues: 1,
      watchers: 0,
      default_branch: 'main',
    },
    sender: {
      login: 'xsahxl',
      id: 21330840,
      node_id: 'MDQ6VXNlcjIxMzMwODQw',
      avatar_url: 'https://avatars.githubusercontent.com/u/21330840?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/xsahxl',
      html_url: 'https://github.com/xsahxl',
      followers_url: 'https://api.github.com/users/xsahxl/followers',
      following_url: 'https://api.github.com/users/xsahxl/following{/other_user}',
      gists_url: 'https://api.github.com/users/xsahxl/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/xsahxl/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/xsahxl/subscriptions',
      organizations_url: 'https://api.github.com/users/xsahxl/orgs',
      repos_url: 'https://api.github.com/users/xsahxl/repos',
      events_url: 'https://api.github.com/users/xsahxl/events{/privacy}',
      received_events_url: 'https://api.github.com/users/xsahxl/received_events',
      type: 'User',
      site_admin: false,
    },
  },
};

test('no trigger data', async () => {
  const eventConfig = {
    github: {
      secret: '9u6g2w8v7x944qh8',
    },
  };
  const res = await verifyLegitimacy(eventConfig as any, pushWithBranch);
  expect(res?.success).toEqual(false);
});

test('git webhook push with branch case', async () => {
  const eventConfig = {
    github: {
      secret: '9u6g2w8v7x944qh8',
      push: {
        branches: {
          prefix: ['feature'],
          precise: ['main'],
          exclude: ['main'],
          include: ['mian'],
        },
      },
    },
  };
  const res = await verifyLegitimacy(eventConfig, pushWithBranch);
  expect(res?.success).toEqual(true);
});

test('git webhook push with tag case', async () => {
  const eventConfig = {
    github: {
      push: {
        tags: {
          prefix: ['feature'],
          precise: ['v0.0.1'],
          exclude: ['1.0.0'],
          include: ['v0.0.1/*'],
        },
      },
    },
  };
  const res = await verifyLegitimacy(eventConfig, pushWithTag);
  expect(res?.success).toEqual(true);
});

test('git webhook pr case', async () => {
  const eventConfig = {
    github: {
      pr: {
        branches: {
          prefix: ['feature'],
          precise: ['main'],
          exclude: ['main'],
          include: ['mian'],
        },
      },
    },
  };
  const res = await verifyLegitimacy(eventConfig, prInputs);
  expect(res?.success).toEqual(true);
});
